-- Version 5: Add products, product_attributes, product_skues, product_sku_attributes table

CREATE TABLE product_attributes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note               VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_by   VARCHAR(255),
    deleted            BOOLEAN DEFAULT FALSE                   NOT NULL,
    version            BIGINT                                  NOT NULL,
    product_id         BIGINT                                  NOT NULL,
    attribute_id       BIGINT                                  NOT NULL,
    value              TEXT    DEFAULT ''                      NOT NULL,
    CONSTRAINT pk_product_attributes PRIMARY KEY (id)
);

CREATE TABLE product_sku_attributes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note               VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_by   VARCHAR(255),
    deleted            BOOLEAN DEFAULT FALSE                   NOT NULL,
    version            BIGINT                                  NOT NULL,
    product_sku_id     BIGINT                                  NOT NULL,
    attribute_id       BIGINT                                  NOT NULL,
    value              TEXT    DEFAULT ''                      NOT NULL,
    CONSTRAINT pk_product_sku_attributes PRIMARY KEY (id)
);

CREATE TABLE product_skues
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note               VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255)                            NOT NULL,
    last_modified_by   VARCHAR(255),
    deleted            BOOLEAN DEFAULT FALSE                   NOT NULL,
    version            BIGINT                                  NOT NULL,
    product_id         BIGINT                                  NOT NULL,
    sku_code           VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_product_skues PRIMARY KEY (id)
);

CREATE TABLE product_skues_product_sku_attributes
(
    product_sku_id            BIGINT NOT NULL,
    product_sku_attributes_id BIGINT NOT NULL
);

CREATE TABLE products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    note                VARCHAR(255),
    created_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255)                            NOT NULL,
    last_modified_by    VARCHAR(255),
    deleted             BOOLEAN DEFAULT FALSE                   NOT NULL,
    version             BIGINT                                  NOT NULL,
    product_id          VARCHAR(50)                             NOT NULL,
    product_name        VARCHAR(100)                            NOT NULL,
    product_description TEXT    DEFAULT ''                      NOT NULL,
    product_category_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE products_product_attributes
(
    product_id            BIGINT NOT NULL,
    product_attributes_id BIGINT NOT NULL
);

CREATE TABLE products_product_skus
(
    product_id      BIGINT NOT NULL,
    product_skus_id BIGINT NOT NULL
);

-- Assign the constraints to each table

ALTER TABLE product_skues_product_sku_attributes
    ADD CONSTRAINT uc_product_skues_product_sku_attributes_productskuattributes UNIQUE (product_sku_attributes_id);

ALTER TABLE product_skues
    ADD CONSTRAINT uc_product_skues_sku_code UNIQUE (sku_code);

ALTER TABLE products
    ADD CONSTRAINT uc_products_product UNIQUE (product_id);

ALTER TABLE products_product_attributes
    ADD CONSTRAINT uc_products_product_attributes_productattributes UNIQUE (product_attributes_id);

ALTER TABLE products
    ADD CONSTRAINT uc_products_product_name UNIQUE (product_name);

ALTER TABLE products_product_skus
    ADD CONSTRAINT uc_products_product_skus_productskus UNIQUE (product_skus_id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_PRODUCT_CATEGORY FOREIGN KEY (product_category_id) REFERENCES product_categories (id);

ALTER TABLE product_attributes
    ADD CONSTRAINT FK_PRODUCT_ATTRIBUTES_ON_ATTRIBUTE FOREIGN KEY (attribute_id) REFERENCES attributes (id);

ALTER TABLE product_attributes
    ADD CONSTRAINT FK_PRODUCT_ATTRIBUTES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_skues
    ADD CONSTRAINT FK_PRODUCT_SKUES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE product_sku_attributes
    ADD CONSTRAINT FK_PRODUCT_SKU_ATTRIBUTES_ON_ATTRIBUTE FOREIGN KEY (attribute_id) REFERENCES attributes (id);

ALTER TABLE product_sku_attributes
    ADD CONSTRAINT FK_PRODUCT_SKU_ATTRIBUTES_ON_PRODUCT_SKU FOREIGN KEY (product_sku_id) REFERENCES product_skues (id);

ALTER TABLE products_product_attributes
    ADD CONSTRAINT fk_proproatt_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_product_attributes
    ADD CONSTRAINT fk_proproatt_on_product_attribute FOREIGN KEY (product_attributes_id) REFERENCES product_attributes (id);

ALTER TABLE products_product_skus
    ADD CONSTRAINT fk_proprosku_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_product_skus
    ADD CONSTRAINT fk_proprosku_on_product_sku FOREIGN KEY (product_skus_id) REFERENCES product_skues (id);

ALTER TABLE product_skues_product_sku_attributes
    ADD CONSTRAINT fk_proskuproskuatt_on_product_sku FOREIGN KEY (product_sku_id) REFERENCES product_skues (id);

ALTER TABLE product_skues_product_sku_attributes
    ADD CONSTRAINT fk_proskuproskuatt_on_product_sku_attribute FOREIGN KEY (product_sku_attributes_id) REFERENCES product_sku_attributes (id);